import { mkdir, unlink, writeFile } from "node:fs/promises";
import path from "node:path";

/**
 * Where attachment bytes live, and the only code that touches them.
 *
 * A filesystem rather than a column: a 5 MB row read on every metadata query is
 * a cost paid whether or not anyone downloads the file, and streaming from disk
 * is what the download endpoint wants anyway (decision D-06).
 *
 * The directory is resolved from this module rather than from the working
 * directory, and via `import.meta.dirname` rather than by trimming
 * `import.meta.url` by hand — `new URL(...).pathname` yields `/C:/Users/...` on
 * Windows, which is not a path any filesystem call accepts. That was a finding
 * from the review of PR #24, and it had already been made twice.
 */

const HERE = import.meta.dirname;

/** `server/uploads`, resolved from this file rather than from the cwd. */
export const UPLOAD_DIR = path.resolve(HERE, "..", "..", "uploads");

/**
 * Resolves a stored name to its absolute path, refusing anything that escapes.
 *
 * Stored names are generated by `storedNameFor`, so this cannot fail today. It
 * is here because "the name is generated" is an invariant maintained elsewhere,
 * and a path traversal that depends on a remote invariant is one refactor from
 * being real (BR-24).
 */
export const pathFor = (storedFilename: string): string => {
  const resolved = path.resolve(UPLOAD_DIR, storedFilename);

  if (path.dirname(resolved) !== UPLOAD_DIR) {
    throw new Error("Stored filename resolved outside the upload directory.");
  }

  return resolved;
};

export const ensureUploadDir = async (): Promise<void> => {
  await mkdir(UPLOAD_DIR, { recursive: true });
};

export const writeAttachment = async (
  storedFilename: string,
  bytes: Buffer
): Promise<void> => {
  await ensureUploadDir();
  await writeFile(pathFor(storedFilename), bytes);
};

/**
 * Deletes a stored file, ignoring the case where it is already gone.
 *
 * This is the compensation in BR-30: if writing the file succeeds but recording
 * its metadata fails, the file is removed so nothing is orphaned. A failure to
 * clean up must not itself become the error the caller sees — they would be
 * told the upload failed for the wrong reason, and it did fail.
 */
export const deleteAttachment = async (
  storedFilename: string
): Promise<void> => {
  try {
    await unlink(pathFor(storedFilename));
  } catch (error) {
    // A file that was never written needs no undoing, so ENOENT is the one
    // outcome that means the job is done. Anything else — a permission
    // failure, a busy handle, a full disk — means the file is still there and
    // now nothing refers to it. Swallowing that hides the orphan it creates,
    // so it is logged and rethrown for the caller to report.
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return;
    }

    throw error;
  }
};
